version: "3.7"
volumes:
  postgres_data:

services:
  database:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
    tty: true
